include ../global.mk
NAMESPACE=observability
RELEASE=loki
HELM_REPO_NAME=grafana
HELM_REPO_URL=https://grafana.github.io/helm-charts
HELM_CHART=loki-stack
HELM_CHART_VERSION=2.3.1
HELM_CHART_VALUES=values.yaml

install: namespace helm
