include ../global.mk
NAMESPACE=observability
RELEASE=prometheus
HELM_REPO_NAME=prometheus-community
HELM_REPO_URL=https://prometheus-community.github.io/helm-charts
HELM_CHART=kube-prometheus-stack
HELM_CHART_VERSION=13.9.1
HELM_CHART_VALUES=values.yaml
HELM_CHART_SECRETS=secrets.enc.yaml

install: namespace helm
